[build]
  command = "npm run build"
  publish = "build"
  functions = ".netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ytdlp-nodejs", "ffmpeg-static"]
  included_files = ["node_modules/ffmpeg-static/**/*"]

[functions."api/*"]
  timeout = 25
